In [1]:
from keras.layers import Input, Dense
from keras.models import Model
import h5py
import sys,pdb
import numpy as np
from sklearn.utils import shuffle

Using TensorFlow backend.


In [2]:
f = h5py.File('mnist_testdata.hdf5', 'r') #small dataset, assume this our full data
print('keys of the dataset: ', list(f.keys())) #useful for seeing the data set name/key
data = f['xdata'][:]
labels = f['ydata'][:]
print(data.shape, labels)
data,labels = shuffle(data, labels)

split=7000
x_train = data[:split, ...]
x_test = data[split:,...]
y_train = labels[:split,...]
y_test = labels[split:,...]
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

keys of the dataset:  ['xdata', 'ydata']
(10000, 784) [[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
7000 train samples
3000 test samples


In [3]:
# Define a functional API model
# Layer 1:                  784 * 32
# Activation 1:             relu
# Layer 2:                  32 * 10
# Activation 2:             softmax
############################################################
# This returns a tensor
inputs = Input(shape=(784,))

# a layer instance is callable on a tensor, and returns a tensor
x = Dense(32, activation='relu')(inputs)
x = Dense(64, activation='relu')(x)
predictions = Dense(10, activation='softmax')(x)

# This creates a model that includes
# the Input layer and three Dense layers
model = Model(inputs=inputs, outputs=predictions)


In [4]:
print(model.summary())


############################################################
# Model compilation
# Must be called before starting training
############################################################
# For a multi-class classification problem
model.compile(optimizer='sgd',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 784)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 32)                25120     
_________________________________________________________________
dense_2 (Dense)              (None, 64)                2112      
_________________________________________________________________
dense_3 (Dense)              (None, 10)                650       
Total params: 27,882
Trainable params: 27,882
Non-trainable params: 0
_________________________________________________________________
None


In [5]:
# Model training
############################################################
# if y_train is not categorical, you may use this 
# or, write your own code to convert
#one_hot_labels = keras.utils.to_categorical(labels, num_classes=10)

model.fit(x_train, y_train, epochs=10, batch_size=32)

Epoch 1/10
7000/7000 [==============================] - 19s 3ms/step - loss: 1.9348 - acc: 0.3731
Epoch 2/10
7000/7000 [==============================] - 1s 147us/step - loss: 1.0568 - acc: 0.7277
Epoch 3/10
7000/7000 [==============================] - 1s 149us/step - loss: 0.6641 - acc: 0.8264
Epoch 4/10
7000/7000 [==============================] - 1s 149us/step - loss: 0.5157 - acc: 0.8589
Epoch 5/10
7000/7000 [==============================] - 1s 148us/step - loss: 0.4375 - acc: 0.8794
Epoch 6/10
7000/7000 [==============================] - 1s 145us/step - loss: 0.3898 - acc: 0.8933
Epoch 7/10
7000/7000 [==============================] - 1s 149us/step - loss: 0.3560 - acc: 0.8986
Epoch 8/10
7000/7000 [==============================] - 1s 141us/step - loss: 0.3322 - acc: 0.9047
Epoch 9/10
7000/7000 [==============================] - 1s 155us/step - loss: 0.3127 - acc: 0.9103
Epoch 10/10
7000/7000 [==============================] - 1s 145us/step - loss: 0.2977 - acc: 0.9143


In [6]:
score = model.evaluate(x_test, y_test, batch_size=32)
print('Test Loss = ', score[0])
print('Test Accuracy = ', score[1])

3000/3000 [==============================] - 0s 74us/step
Test Loss =  0.32823279345035555
Test Accuracy =  0.9043333333333333
